title: Ashish Gawali
author: ashish-gawali
email: gawaliashish924@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I am trying to comeup with a personal website. Did not want to just use a theme and go ahead, intended to learn what github pages and jenkyll is about.

# social links
social_links:
  twitter: normalGuy924 # DO NOT include the @ character, or else the build will fail!
  github:  ashish-gawali # DO NOT include the @ character, or else the build will fail!
  linkedin: ashish-anil-gawali

show_excerpts: true # set to false to remove excerpts on the homepage
