title: Ashish Gawali
author: ashish-gawali
email: gawaliashish924@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  I am trying to comeup with a personal website. Did not want to just use a theme and go ahead, intended to learn what github pages and jenkyll is about.


#twitter_username: normalGuy924 # DO NOT include the @ character, or else the build will fail!
#github_username:  ashish-gawali # DO NOT include the @ character, or else the build will fail!
#linkedin_username: ashish-anil-gawali

show_excerpts: true # set to false to remove excerpts on the homepage

#theme: minima
markdown: kramdown

permalink: /blog/:year/:month/:day/:title
plugins:
 - jekyll-seo-tag
